[package]
name = "solo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "solo"
path = "src/lib.rs"

[dependencies]
log = "0.4"
env_logger = "0.7.1"
tokio = {version = "1.12.0", features = ["process"]}