name: Build and run tests
on: [push]

jobs:
  build:
    env:
      RUST_LOG: debug
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Select nightly toolchain
        run: rustup default nightly
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Install system dependencies
        run: sudo apt-get install libudev-dev libdbus-1-dev libsodium-dev
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test --verbose --features hid-device-tests
      - name: Run u2f_hid example (virtual key)
        run: cargo run --example u2f_hid --features virtual-hid-device
      # - name: Run webauthn_hid example (virtual key)
      #   run: cargo run --example webauthn_hid --features virtual-hid-device
